
import React, { useState, useEffect } from 'react';
import { PulseCanvas } from './components/PulseCanvas';
import { Controls } from './components/Controls';
import { Header } from './components/Header';
import { Hero } from './components/Hero';
import { Repository } from './components/Repository';
import { Info } from './components/Info';
import { Admin } from './components/Admin';
import { Login } from './components/Login';
import { AssetDetail } from './components/AssetDetail';
import { DEFAULT_CONFIG, DEFAULT_HOMEPAGE_CONFIG } from './constants';
import { ASSETS as INITIAL_ASSETS } from './data';
import { AppConfig, ViewState, Asset, HomepageConfig } from './types';
import { supabase } from './supabaseClient';

export default function App() {
  // --- Background State ---
  const [bgConfig, setBgConfig] = useState<AppConfig>(DEFAULT_CONFIG);
  const [showBgControls, setShowBgControls] = useState(false);

  // --- App State ---
  const [currentView, setCurrentView] = useState<ViewState>('home');
  const [assets, setAssets] = useState<Asset[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  
  // Homepage Content State (Still in LocalStorage for simplicity of MVP, could be moved to DB later)
  const [homeConfig, setHomeConfig] = useState<HomepageConfig>(() => {
    const saved = localStorage.getItem('gl_home_config');
    return saved ? JSON.parse(saved) : DEFAULT_HOMEPAGE_CONFIG;
  });

  const [selectedAssetId, setSelectedAssetId] = useState<number | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  // --- Effects ---

  // 1. Check Auth Status
  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setIsAuthenticated(!!session);
    });

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((_event, session) => {
      setIsAuthenticated(!!session);
    });

    return () => subscription.unsubscribe();
  }, []);

  // 2. Fetch Assets from DB
  useEffect(() => {
    fetchAssets();
  }, []);

  const fetchAssets = async () => {
    setIsLoading(true);
    const { data, error } = await supabase
      .from('assets')
      .select('*')
      .order('created_at', { ascending: false });

    if (!error && data) {
      setAssets(data as Asset[]);
    } else {
      console.error('Error fetching assets:', error);
      // Fallback for demo if DB is empty/not connected
      if (assets.length === 0) setAssets(INITIAL_ASSETS);
    }
    setIsLoading(false);
  };

  // Save homepage config to LocalStorage
  useEffect(() => {
    localStorage.setItem('gl_home_config', JSON.stringify(homeConfig));
  }, [homeConfig]);

  // --- Handlers ---
  const handleAssetSelect = (id: number) => {
    setSelectedAssetId(id);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleBackToRepo = () => {
    setSelectedAssetId(null);
  };

  const handleSaveAsset = async (asset: Asset) => {
    // Optimistic Update
    setAssets(prev => {
      const exists = prev.find(a => a.id === asset.id);
      if (exists) return prev.map(a => a.id === asset.id ? asset : a);
      return [asset, ...prev];
    });

    // DB Update
    // Strip ID if it's a temporary timestamp-based ID (large number) to allow DB to auto-increment
    // However, for simplicity, Supabase can handle the upsert if ID matches.
    // If it's a NEW asset (generated by Date.now()), we might want to let Postgres handle ID.
    // But since we use upsert, passing the ID is fine if we want client-side control.
    
    // Note: Supabase needs 'gallery' to be a PostgreSQL array.
    
    const { error } = await supabase
      .from('assets')
      .upsert(asset);

    if (error) {
      console.error('Error saving asset:', error);
      alert('Failed to save to database. Check console.');
      fetchAssets(); // Revert
    } else {
      fetchAssets(); // Refresh to get real IDs if generated
    }
  };

  const handleDeleteAsset = async (id: number) => {
    setAssets(prev => prev.filter(a => Number(a.id) !== Number(id)));

    const { error } = await supabase
      .from('assets')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting asset:', error);
      fetchAssets();
    }
  };

  const handleSaveHomeConfig = (config: HomepageConfig) => {
    setHomeConfig(config);
  };

  // --- View Rendering ---
  const renderContent = () => {
    if (isLoading && assets.length === 0) {
      return (
        <div className="flex items-center justify-center h-[50vh] text-yellow-400 font-mono animate-pulse">
          INITIALIZING_SYSTEM...
        </div>
      );
    }

    // If an asset is selected, show Detail View (overlaying current section)
    if (selectedAssetId) {
      const asset = assets.find(a => a.id === selectedAssetId);
      if (asset) {
        return <AssetDetail asset={asset} onBack={handleBackToRepo} />;
      }
    }

    switch (currentView) {
      case 'home':
        return (
          <Hero 
            featuredAssets={assets.filter(a => a.featured).slice(0, 2)} 
            config={homeConfig}
            onAssetSelect={handleAssetSelect}
            onNavigateToRepo={() => setCurrentView('repository')}
          />
        );
      case 'repository':
        return (
          <Repository 
            assets={assets.filter(a => !a.section || a.section === 'repository')} 
            onAssetSelect={handleAssetSelect} 
            title="REPOSITORY"
            subtitle="INDEX OF AVAILABLE TOOLS"
          />
        );
      case 'works':
        return (
          <Repository 
            assets={assets.filter(a => a.section === 'works')} 
            onAssetSelect={handleAssetSelect}
            title="WORKS"
            subtitle="SELECTED VISUAL PROJECTS"
          />
        );
      case 'info':
        return <Info />;
      case 'admin':
        return isAuthenticated ? (
          <Admin 
            assets={assets} 
            homeConfig={homeConfig}
            onSave={handleSaveAsset} 
            onDelete={handleDeleteAsset}
            onSaveHomeConfig={handleSaveHomeConfig}
            onCancel={() => setCurrentView('home')}
          />
        ) : (
          <Login onLogin={() => setIsAuthenticated(true)} />
        );
      default:
        return (
          <Hero 
            featuredAssets={assets} 
            config={homeConfig}
            onAssetSelect={handleAssetSelect} 
            onNavigateToRepo={() => setCurrentView('repository')} 
          />
        );
    }
  };

  return (
    <div className="relative w-full min-h-screen bg-[#09090b] text-[#eee] selection:bg-yellow-400 selection:text-black flex flex-col overflow-x-hidden">
      
      {/* --- Background Layer --- */}
      <div className="fixed inset-0 z-0 pointer-events-auto">
        <PulseCanvas config={bgConfig} />
      </div>

      {/* --- Foreground Layer --- */}
      <div className="relative z-10 flex flex-col min-h-screen pointer-events-none">
        {/* Enable pointer events only for interactive children */}
        <div className="pointer-events-auto w-full">
           <Header currentView={currentView} setCurrentView={(view) => {
             setCurrentView(view);
             setSelectedAssetId(null);
           }} />
        </div>
        
        <main className="flex-grow w-full pointer-events-auto">
          {renderContent()}
        </main>

        <footer className="h-10 border-t border-[#333] bg-[#111] flex items-center justify-center text-[10px] text-gray-600 font-mono z-10 mt-auto shrink-0 w-full pointer-events-auto">
          GETLEMONS.XYZ // EST. 2024
        </footer>
      </div>

      {/* --- Hint Text --- */}
      <div className="fixed bottom-6 left-6 z-20 pointer-events-none select-none">
        <p className="text-[10px] text-gray-500 font-mono tracking-widest opacity-60">
          CLICK & HOLD TO EMIT //
        </p>
      </div>

      {/* --- Background Controls Toggle --- */}
      {showBgControls && (
        <Controls config={bgConfig} onChange={setBgConfig} />
      )}
      <button
        onClick={() => setShowBgControls(!showBgControls)}
        className="fixed bottom-4 right-4 z-50 p-2 bg-black/50 hover:bg-black text-gray-500 hover:text-white border border-[#333] rounded-full transition-all pointer-events-auto"
        title="Background Settings"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="3"></circle>
          <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
        </svg>
      </button>

    </div>
  );
}
